wsim rv32gc /home/mabdullab/cvw/riscof_work/src/cadd-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/caddi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/caddi16sp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/caddi4spn-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/cand-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/candi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/cbeqz-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/cbnez-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/cebreak-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/cj-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/cjal-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/clbu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/clh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/clhu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/cli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/clui-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/clw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/clwsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/cmul-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/cmv-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/cnop-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/cnot-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/cor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/csb-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/csext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/csext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/csh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/cslli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/csrai-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/csrli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/csub-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/csw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/cswsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/cxor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/czext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/czext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/misalign1-cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/riscof_work/src/misalign1-cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cadd-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi16sp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi4spn-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cand-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/candi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbeqz-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbnez-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cebreak-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cj-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjal-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clbu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clhu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clui-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clwsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmul-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmv-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnop-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnot-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csb-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cslli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrai-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csub-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cswsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cxor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cadd-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi16sp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi4spn-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cand-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/candi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbeqz-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbnez-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cebreak-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cj-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjal-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clbu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clhu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clui-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clwsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmul-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmv-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnop-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnot-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csb-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cslli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrai-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csub-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cswsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cxor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cadd-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi16sp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi4spn-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cand-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/candi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbeqz-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbnez-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cebreak-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cj-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjal-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clbu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clhu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clui-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clwsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmul-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmv-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnop-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnot-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csb-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cslli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrai-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csub-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cswsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cxor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cadd-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi16sp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi4spn-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cand-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/candi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbeqz-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbnez-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cebreak-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cj-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjal-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clbu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clhu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clui-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clwsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmul-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmv-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnop-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnot-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csb-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cslli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrai-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csub-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cswsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cxor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cadd-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi16sp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi4spn-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cand-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/candi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbeqz-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbnez-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cebreak-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cj-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjal-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clbu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clhu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clui-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clwsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmul-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmv-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnop-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnot-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csb-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cslli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrai-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csub-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cswsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cxor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cadd-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi16sp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi4spn-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cand-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/candi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbeqz-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbnez-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cebreak-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cj-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjal-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clbu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clhu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clui-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clwsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmul-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmv-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnop-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnot-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csb-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cslli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrai-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csub-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cswsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cxor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cadd-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi16sp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi4spn-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cand-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/candi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbeqz-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbnez-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cebreak-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cj-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjal-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clbu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clhu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clui-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clwsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmul-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmv-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnop-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnot-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csb-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cslli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrai-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csub-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cswsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cxor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cadd-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi16sp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi4spn-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cand-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/candi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbeqz-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbnez-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cebreak-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cj-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjal-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clbu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clhu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clui-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clwsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmul-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmv-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnop-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnot-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csb-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cslli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrai-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csub-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cswsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cxor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cadd-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi16sp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi4spn-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cand-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/candi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbeqz-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbnez-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cebreak-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cj-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjal-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clbu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clhu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clui-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clwsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmul-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmv-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnop-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnot-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csb-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cslli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrai-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csub-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cswsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cxor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cadd-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi16sp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi4spn-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cand-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/candi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbeqz-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbnez-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cebreak-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cj-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjal-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clbu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clhu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clui-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clwsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmul-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmv-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnop-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnot-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csb-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cslli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrai-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csub-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cswsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cxor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cadd-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi16sp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/caddi4spn-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cand-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/candi-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbeqz-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cbnez-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cebreak-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cj-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjal-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cjr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clbu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clhu-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clui-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/clwsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmul-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cmv-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnop-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cnot-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csb-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csh-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cslli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrai-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csrli-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csub-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/csw-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cswsp-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/cxor-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.b-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/czext.h-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjalr-01.S/dut/main.elf 
wsim rv32gc /home/mabdullab/cvw/addins/cvw-arch-verif/riscof_work/src/misalign1-cjr-01.S/dut/main.elf 
